/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * aapt tool from the resource data it found.  It
 * should not be modified by hand.
 */

package org.puredata.android.service;

public final class R {
    public static final class array {
        public static int inchannels_labels = 0x7f070002;
        public static int inchannels_values = 0x7f070003;
        public static int outchannels_labels = 0x7f070004;
        public static int outchannels_values = 0x7f070005;
        public static int srate_labels = 0x7f070000;
        public static int srate_values = 0x7f070001;
    }

    public static final class attr {
    }

    public static final class drawable {
        public static int din5 = 0x7f020000;
        public static int icon = 0x7f020001;
    }

    public static final class id {
        public static int paired_devices = 0x7f090001;
        public static int title_paired_devices = 0x7f090000;
    }

    public static final class layout {
        public static int device_list = 0x7f030000;
        public static int device_name = 0x7f030001;
    }

    public static final class raw {
        public static int extra_abs = 0x7f050000;
        public static int silence = 0x7f050001;
    }

    public static final class string {
        public static int none_paired = 0x7f060001;
        public static int pref_key_inchannels = 0x7f060010;
        public static int pref_key_outchannels = 0x7f060013;
        public static int pref_key_srate = 0x7f06000d;
        public static int pref_sum = 0x7f06000c;
        public static int pref_sum_inchannels = 0x7f060012;
        public static int pref_sum_outchannels = 0x7f060015;
        public static int pref_sum_srate = 0x7f06000f;
        public static int pref_title = 0x7f06000b;
        public static int pref_title_inchannels = 0x7f060011;
        public static int pref_title_outchannels = 0x7f060014;
        public static int pref_title_srate = 0x7f06000e;
        public static int select_device = 0x7f060000;
        public static int title_no_paired_devices = 0x7f060003;
        public static int title_no_usb_devices_available = 0x7f060008;
        public static int title_no_usb_midi_input_available = 0x7f060009;
        public static int title_no_usb_midi_output_available = 0x7f06000a;
        public static int title_paired_devices = 0x7f060002;
        public static int title_select_bluetooth_device = 0x7f060004;
        public static int title_select_usb_midi_device = 0x7f060005;
        public static int title_select_usb_midi_input = 0x7f060006;
        public static int title_select_usb_midi_output = 0x7f060007;
    }

    public static final class style {
        public static int DisableSoundEffects = 0x7f080000;
    }

    public static final class xml {
        public static int preferences = 0x7f040000;
    }
}
